name: Build single

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Download source
        uses: actions/download-artifact@v4
        with:
          name: src-${{ inputs.branch }}
          path: assets

      - uses: actions/download-artifact@v4
        with:
          name: buildenv
          path: assets

      - name: Build
        run: |
          zstdcat assets/buildenv.tar.zst | podman load
          podman run --rm --cap-add=sys_admin -v $PWD:/mnt -w /mnt mingw-lite/buildenv \
            ./main.py --branch ${{ inputs.branch }} --profile ${{ inputs.profile }}

      - uses: actions/upload-artifact@v4
        with:
          name: mingw${{ inputs.profile }}-${{ inputs.branch }}
          path: dist

  test_on_linux:
    name: Test on Linux
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Enable multiarch
        run: |
          sudo dpkg --add-architecture i386

      - uses: ConorMacBride/install-package@v1
        with:
          apt: libarchive-tools wine

      # apt install wine-binfmt seems not work
      - name: Register wine binfmt
        run: |
          echo ':DOSWin:M::MZ::/usr/bin/wine:' | sudo tee /proc/sys/fs/binfmt_misc/register

      - uses: actions/download-artifact@v4
        with:
          name: mingw${{ inputs.profile }}-${{ inputs.branch }}
          path: dist

      - name: Test
        run: |
          ./test.py --branch ${{ inputs.branch }} --profile ${{ inputs.profile }} -v

  test_on_windows:
    name: Test on Windows
    runs-on: windows-2022
    needs: build

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: mingw${{ inputs.profile }}-${{ inputs.branch }}
          path: dist

      - name: Setup bsdtar
        run: |
          New-Item -ItemType Directory -Path assets -Force
          Invoke-WebRequest `
            -Uri https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-v1.5.7-win64.zip `
            -OutFile assets/zstd-v1.5.7-win64.zip
          Expand-Archive -Path assets/zstd-v1.5.7-win64.zip -DestinationPath assets
          $system32 = [Environment]::SystemDirectory
          Copy-Item -Path assets/zstd-v1.5.7-win64/zstd.exe -Destination "$system32/zstd.exe"
          New-Item -ItemType SymbolicLink -Path "$system32/bsdtar.exe" -Target tar.exe

      - name: Install Python Package
        run: |
          pip install packaging

      - name: Test
        run: |
          python test.py --branch ${{ inputs.branch }} --profile ${{ inputs.profile }} --build x86_64-w64-mingw32 -v
